"""
Phase B: Shuffle answer positions for MC/pbq_scenario questions.
Phase C: Improve weak distractors across all domain files.
"""
import json, random, os, copy

BASE = r"C:\Users\kamix\Desktop\security-plus-study\data"

# ─────────────────────────────────────────────────────────────
# PHASE C  –  distractor replacements keyed by question id
#             Format: { "Q-ID": { "option_key": "new_text" } }
# ─────────────────────────────────────────────────────────────
FIXES = {
    # ── Domain 1 ─────────────────────────────────────────────
    "D1-001": {
        "D": "Perimeter-based security architecture relying on trusted internal network zones"
    },
    "D1-014": {
        "C": "Restricted activity enforcement via a software-defined policy engine"
    },

    # ── Domain 2 ─────────────────────────────────────────────
    "D2-020": {
        "C": "Rooting the device to remove carrier restrictions and install custom firmware",
        "D": "Enrolling the device in an unauthorized MDM profile from a third-party provider"
    },
    "D2-031": {
        "C": "Enabling NTP synchronisation so the server audit log timestamps are accurate",
        "D": "Configuring the server to forward all event logs to the centralised SIEM platform",
        "E": "Granting local administrator rights to all standard users to simplify troubleshooting"
    },

    # ── Domain 3 ─────────────────────────────────────────────
    "D3-009": {
        "D": "Software-defined wide area network (SD-WAN)"
    },
    "D3-015": {
        "D": "Data subject to active regulatory classification review"
    },
    "D3-028": {
        "C": "Link aggregation using 802.3ad LACP for increased throughput"
    },

    # ── Domain 4 ─────────────────────────────────────────────
    "D4-003": {
        "D": "CIS Benchmark compliance assessment profile"
    },
    "D4-004": {
        "A": "WPA2-Enterprise using EAP-TTLS with certificate-based authentication"
    },
    "D4-005": {
        "B": "Enabling biometric authentication as the sole unlock method, removing the PIN requirement",
        "D": "Enrolling the device in a mobile application management (MAM) solution to control app access",
        "E": "Deploying a VPN client configured to route all corporate traffic through headquarters"
    },
    "D4-006": {
        "D": "Apply vendor-provided firmware updates directly to production devices without staging or rollback testing"
    },
    "D4-010": {
        "B": "Encrypt the drives with BitLocker prior to donating the devices to charity, without performing a full wipe",
        "D": "Transfer devices to a certified electronics recycler under a standard terms-of-service agreement, without requesting a certificate of destruction",
        "E": "Reimage the laptops with a clean OS installation, treating the reimage as equivalent to a NIST-compliant data sanitization"
    },
    "D4-015": {
        "B": "Apply every available patch within 24 hours of release, bypassing normal change management and testing procedures",
        "D": "Categorise all discovered vulnerabilities as low risk in the tracking tool to reduce the remediation backlog",
        "E": "Delegate all vulnerability remediation decisions to individual system owners with no centralised tracking or SLA requirements"
    },
    "D4-018": {
        "C": "Security orchestration, automation and response (SOAR) platform"
    },
    "D4-020": {
        "B": "It provides real-time automated threat blocking by analysing log content against known attack signatures",
        "C": "It automatically remediates vulnerabilities discovered in the aggregated log stream before they can be exploited",
        "D": "It reduces each server individual storage requirements by offloading all log processing to the central appliance"
    },
    "D4-021": {
        "B": "Archive all triggered alerts automatically to long-term storage without analyst review to preserve potential evidence",
        "D": "Escalate every alert generated by this rule to a senior analyst without any initial triage or suppression",
        "E": "Reduce logging verbosity on the monitored system to generate fewer raw log entries, indirectly lowering alert volume"
    },
    "D4-023": {
        "B": "Web content proxy with agent-based URL inspection deployed on each endpoint",
        "D": "Network access control (NAC) with device posture assessment at network entry points"
    },
    "D4-026": {
        "B": "Rule 2 is evaluated before Rule 1 because deny rules always take precedence over allow rules by default",
        "C": "The deny rule applies only to new TCP connection requests and does not affect already-established sessions"
    },
    "D4-029": {
        "B": "Convert the terminated employee account to a shared service account for their team to maintain workflow continuity",
        "D": "Transfer the terminated employee VPN certificate to a named successor to ensure continuity of remote access",
        "E": "Retain the terminated employee Active Directory account in a disabled state with full permissions for potential rehire"
    },
    "D4-031": {
        "B": "Reducing mean time to detect and contain security incidents by automating alert generation and initial triage",
        "C": "Enabling per-server customisation of security settings based on each system individual risk classification",
        "D": "Generating real-time compliance reports showing each server adherence to the approved configuration baseline"
    },
    "D4-032": {
        "D": "Privileged access management (PAM) workflow for temporary elevated permission requests"
    },
    "D4-033": {
        "B": "Automated security tools may generate a higher volume of low-fidelity alerts than manual processes, increasing analyst workload",
        "D": "Automation requires significant upfront vendor licensing investment that typically exceeds the cost of equivalent manual processes",
        "E": "Regulatory frameworks universally prohibit automated security controls from taking any enforcement action without explicit human approval"
    },
    "D4-035": {
        "C": "Configuration drift from an undocumented baseline"
    },
    "D4-037": {
        "D": "E-discovery legal hold acknowledgement form"
    },
    "D4-038": {
        "C": "Tabletop exercises are most appropriate for executive leadership, while simulations are reserved for technical operations staff",
        "D": "Simulations provide more value than tabletop exercises and should fully replace them in security-mature organisations",
        "E": "A tabletop exercise and a simulation should always be conducted simultaneously to validate both discussion and technical capabilities at once"
    },
    "D4-041": {
        "C": "DNS query logs from the organisation internal recursive resolver",
        "D": "NetFlow traffic metadata collected at the network perimeter switches"
    },
    "D4-043": {
        "C": "The IT asset inventory database showing the current assigned owner of all workstations",
        "D": "The organisation data classification policy for the file types suspected to have been exfiltrated",
        "E": "Endpoint vulnerability scan results from the previous quarter for all systems involved in the suspected incident"
    },
    "D4-045": {
        "D": "The network physical cable-plant documentation identifying all direct connections to the suspicious workstation"
    },

    # ── Domain 5 ─────────────────────────────────────────────
    "D5-004": {
        "C": "Vulnerability disclosure and coordinated patching process"
    },
    "D5-014": {
        "D": "Independent third-party security certification audit report"
    },
    "D5-015": {
        "D": "Contractual indemnification clause limiting vendor liability"
    },
    "D5-017": {
        "C": "Request a signed letter of commitment from the vendor pledging security improvements before the next contract renewal"
    },
    "D5-018": {
        "C": "Risk transfer strategy involving cybersecurity insurance"
    },
    "D5-020": {
        "C": "The right for an organisation compliance auditors to access all personal data held on its systems without notifying data subjects",
        "D": "The right for an organisation to retain personal data beyond its stated retention period if it may be needed for future business purposes",
        "E": "The right for organisations to use personal data for any secondary purpose, provided the data is first pseudonymised"
    },
    "D5-021": {
        "C": "Formally accept the identified training gap as an organisational risk and add it to the risk register without immediate remediation"
    },
    "D5-023": {
        "D": "Regulatory compliance examination by a government-appointed inspector"
    },
    "D5-028": {
        "D": "A business email compromise (BEC) post-incident review"
    },
}


def apply_fixes(questions):
    """Apply Phase C distractor replacements."""
    fixed = 0
    for q in questions:
        qid = q.get("id")
        if qid not in FIXES:
            continue
        replacements = FIXES[qid]
        if not replacements:
            continue
        opts = q.get("options")
        if opts is None:
            continue
        for key, new_text in replacements.items():
            if key in opts:
                opts[key] = new_text
                fixed += 1
    return fixed


def shuffle_options(q, rng):
    """
    Phase B: Fisher-Yates shuffle of A/B/C/D for MC and pbq_scenario.
    Returns a NEW question dict; does not mutate the original.
    """
    fmt    = q.get("format", "")
    answer = q.get("answer")
    opts   = q.get("options")

    if fmt not in ("multiple_choice", "pbq_scenario"):
        return q
    if isinstance(answer, list):   # multi_select – skip
        return q
    if opts is None or answer not in opts:
        return q

    correct_text = opts[answer]
    letters = list(opts.keys())
    texts   = [opts[k] for k in letters]

    for i in range(len(texts) - 1, 0, -1):
        j = rng.randint(0, i)
        texts[i], texts[j] = texts[j], texts[i]

    new_opts   = dict(zip(letters, texts))
    new_answer = next(k for k, v in new_opts.items() if v == correct_text)

    new_q = dict(q)
    new_q["options"] = new_opts
    new_q["answer"]  = new_answer
    return new_q


def audit(all_qs, label=""):
    counts = {"A": 0, "B": 0, "C": 0, "D": 0, "multi": 0, "other": 0}
    for q in all_qs:
        a = q.get("answer")
        if isinstance(a, list):
            counts["multi"] += 1
        elif a in counts:
            counts[a] += 1
        else:
            counts["other"] += 1

    single = counts["A"] + counts["B"] + counts["C"] + counts["D"]
    total  = single + counts["multi"] + counts["other"]
    print(f"\n{'-'*60}")
    print(f"  {label}")
    print(f"{'-'*60}")
    print(f"  A={counts['A']:3d}  B={counts['B']:3d}  C={counts['C']:3d}  D={counts['D']:3d}  "
          f"multi={counts['multi']:3d}  total={total}")
    if single:
        pA = counts["A"]/single*100
        pB = counts["B"]/single*100
        pC = counts["C"]/single*100
        pD = counts["D"]/single*100
        print(f"  Single-answer %:  A={pA:.1f}%  B={pB:.1f}%  C={pC:.1f}%  D={pD:.1f}%")
    return counts


def main():
    rng = random.Random(42)

    all_before = []
    all_after  = []
    total_fixes = 0

    for n in range(1, 6):
        path = os.path.join(BASE, f"questions-{n}.json")
        with open(path, encoding="utf-8") as f:
            questions = json.load(f)

        all_before.extend(copy.deepcopy(questions))

        fixes = apply_fixes(questions)
        total_fixes += fixes

        shuffled = [shuffle_options(q, rng) for q in questions]
        all_after.extend(shuffled)

        with open(path, "w", encoding="utf-8") as f:
            json.dump(shuffled, f, indent=2, ensure_ascii=False)
        print(f"  Saved questions-{n}.json  ({len(shuffled)} questions, {fixes} distractor fixes this file)")

    print(f"\n  Total distractor option replacements: {total_fixes}")

    audit(all_before, "BEFORE (original)")
    audit(all_after,  "AFTER  (shuffled)")

    before_count = len(all_before)
    after_count  = len(all_after)
    print(f"\n  Question count unchanged: {before_count} -> {after_count}  "
          f"{'OK' if before_count == after_count else 'MISMATCH'}")

    bad = [q["id"] for q in all_after
           if isinstance(q.get("options"), dict)
           and any("none of the above" in v.lower() or "all of the above" in v.lower()
                   for v in q["options"].values())]
    print(f"  'None/All of the above' found: {len(bad)}  {'none' if not bad else str(bad)}")

    ms_issues = 0
    for b, a in zip(all_before, all_after):
        if isinstance(b.get("answer"), list):
            if b["answer"] != a.get("answer"):
                ms_issues += 1
    print(f"  Multi-select answers modified: {ms_issues}  {'none' if not ms_issues else 'PROBLEM'}")
    print()


if __name__ == "__main__":
    main()
